### PR TITLE
Added POST, PUT, PATCH, DELETE and OPTIONS to the methods

### PR DESCRIPTION
**Pull request by ghost**
Added POST, PUT, PATCH, DELETE and OPTIONS to the HTTP methods the app tries. There's a --check-all flag to include everything or it is possible to specify each method to test like --check-<Method Name>.

### CODE REVIEW

**Comment by dub-flow** [comment]
Thanks for the Pull Request! I will be OOO for the rest of the week joining Black Hat Europe, but will be reviewing this afterward.

**Comment by dub-flow** [comment]
@nicolasrod thanks again for the Pull Request! 😊

I reviewed it and like the idea of allowing users to check multiple HTTP methods. I love checking `DELETE` for the URLs. Maybe we can further improve this and only run `DELETE` on URLs that have some sort of an ID in the URL (e.g. `<host>/users/15`), but that's future work!

I think `OPTIONS` can make sense for misconfigured servers potentially.

However, I'm wondering how successful sending a `POST` / `PATCH` / `PUT` request without a body is. Did you by any chance play around with this on some test apps? Can this actually find broken access control? 

My concern is that with an empty or incorrect body, the app would always just send back an error regardless of if the user is authorized or not. What are your thoughts on this?

**Comment by ghost** [comment]
`However, I'm wondering how successful sending a POST / PATCH / PUT request without a body is. Did you by any chance play around with this on some test apps? Can this actually find broken access control?`

Hey @dub-flow. Yeah, in some cases sending POST/PUT request with no body and query parameters make certain web server implementations (old ones mainly) take those query parameters and use them as POST parameters. In the cases I found, the application got confused between GET and POST request and parameter validation. To be honest, it's not usual but I end up checking anyway just in case. 

`My concern is that with an empty or incorrect body, the app would always just send back an error regardless of if the user is authorized or not. What are your thoughts on this?`

With an incorrect body, I guess so (and if it's behind a cloud load balancer, for sure). But with an empty body, it is a valid request. You could send a request to change state or use HTTP headers to extract information for the request. Sadly, it's not so unusual in my experience.

**Comment by dub-flow** [comment]
Right, if it's like PHP or something and they use `$_REQUEST` instead of `$_POST`, then potentially we could trigger a `POST` / `PUT` / `PATCH` request without an HTTP body.

Probably unusual but I guess worth having as a case to test.

I will be on a business trip for most of this week again but will be back to normal work from next week and then give this a test, and then merge it.

**Pull request merged**
